language: java
jdk: oraclejdk8
before_install:
  - wget https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.1.69/forge-1.14.4-28.1.69-mdk.zip
  - unzip -n forge-1.14.4-28.1.69-mdk.zip
  - rm forge-1.14.4-28.1.69-mdk.zip
install: ./gradlew setupCiWorkspace
script: ./gradlew build