language: java
jdk: oraclejdk8
dist: trusty
before_install:
  - wget https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.15.1-30.0.30/forge-1.15.1-30.0.30-mdk.zip
  - unzip -n forge-1.15.1-30.0.30-mdk.zip
  - rm forge-1.15.1-30.0.30-mdk.zip
  - chmod +x gradlew
#install: ./gradlew setupCiWorkspace
script: ./gradlew build