modLoader="javafml"
loaderVersion="[30.0]"
credits="Developed by Doc Bok"
[[mods]]
    modId="docwheat"
    version="0.1"
    displayName="Bok's Wheat Mod" #mandatory
    description='''Changes wheat so there are more gameplay options. Several new types of wheat, lots of new food recipes, and a new villager type!'''
    [[dependencies.docwheat]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.15.1,)"
        ordering="NONE"
        side="BOTH"